### ISSUE TITLE
 IOSPlayerLib 播放器库

### ISSUE THREAD

**Issue by BinBear** [SeaHub/Beacon#6]
获取由爱奇艺官方提供的 IOSPlayerLib 播放器库，请问一下，这个库需要在哪获取呢

**Comment by krayc425** [comment]
https://pan.baidu.com/s/1gfxfyc7 你可以在这里下载，这是最主要的 libav.a 文件

**Comment by Desgard** [comment]
@BinBear 这个是比赛用的 Lib，昨天已经结束，不知道之后其 Lib 中的功能以及视频ID是否有变化。

**Comment by BinBear** [comment]
@Desgard 嗯嗯

**Comment by SeaHub** [comment]
请从 @songkuixi 提供的地址获取，readme 已更新，库在结束比赛后应该也可以用，爱奇艺相关获取视频的接口可能会关闭。

**Comment by BinBear** [comment]
这个地址下载下来的只有一个libav.a静态库，并没有QYPlayerController.h头文件啊
![image](https://user-images.githubusercontent.com/13587915/27282704-aa430772-5523-11e7-9008-5b3cc13dc6f4.png)
好需要ASI支持？

**Comment by krayc425** [comment]
剩下的在这里下载：
[include.zip](https://github.com/SeaHub/Beacon/files/1084688/include.zip)

解压后 include 文件夹和 libav.a 同级

**Comment by BinBear** [comment]
@songkuixi 👌
